# Файл docker-compose должен начинаться с тега версии.
version: '3.4'

services:
  webapi1:
    image: ${DOCKER_REGISTRY-}webapi1
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=db;Database=FilmDiary;User=sa;Password=Pass5678;MultipleActiveResultSets=True
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "SA_PASSWORD=Pass5678"
      - "ACCEPT_EULA=Y"
    container_name: mssql
    
