name: dotnet test

on:
  push:
    paths:
      - "**.cs"
      - ".editorconfig"

jobs:
  check-tests:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Run all test
        run: dotnet test